title: QMK Configurator
email: hello@qmk.fm
show_downloads: true
description: QMK for potatoes - an open source configurator for QMK Firmware (only the AVR boards right now)
baseurl: ""
url: ""
github_username: ""
repository: ""
theme: jekyll-theme-minimal
